# Generated by Django 5.2.6 on 2025-11-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=255, unique=True)),
                ('dataset', models.CharField(max_length=255, unique=True)),
                ('node', models.CharField(max_length=255, unique=True)),
                ('prompt', models.TextField()),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompts',
                'unique_together': {('technique', 'dataset', 'node')},
            },
        ),
    ]
